# Generated by Django 5.1.2 on 2024-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=100),
        ),
    ]
